ROOT	= ..
include $(ROOT)/build.variables
default : all
PROJ_INCLUDES := -I$(OA_INC) -I../aividmfilesys
PROJ_NAME = oaAiviDMFileSysBase
-include local.rules
include $(ROOT)/src.rules
include Hfiles.defs
include $(ROOT)/lib.rules
